### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by alan-agius4** [jsonjoy-com/base64#1]
Can you please add licenses to your NPM packages?

Our CI is failing because your packages are unlicensed as in Angular CLI we do not allow un-licensed packages to be consumed.

<img width="322" alt="IMG_0563" src="https://github.com/jsonjoy-com/base64/assets/17563226/1e5c5312-87de-48b0-bec2-0c7a8662a413">

I am happy to open PRs if you let me know which license you’d like to use.

PS: I also, tried to reach out via twitter: https://x.com/alanagius4/status/1785922108909813824?s=46&t=knjEp6bF9s747yZwI_PLmw

**Comment by streamich** [comment]
done

**Comment by alan-agius4** [comment]
Thanks for this @streamich, when should we expect a release of these packages with the fix? Thanks.
